fn main() {
    // tauri-build embeds the bundle icons into the Windows resource (.res) but
    // never watches the icon files (it only emits rerun-if-changed for the
    // config, capabilities and frontend dist). Because those directives already
    // disable cargo's default "rerun on any change" behaviour, replacing an
    // icon would relink the stale .res into fresh binaries. Watch them here so
    // icon updates always recompile the resource.
    for icon in [
        "icons/32x32.png",
        "icons/128x128.png",
        "icons/128x128@2x.png",
        "icons/icon.icns",
        "icons/icon.ico",
    ] {
        println!("cargo:rerun-if-changed={icon}");
    }

    // Declaring the app commands makes tauri-build auto-generate
    // `permissions/autogenerated/allow-*.toml` files for each command.
    // Without them, the app's ACL manifest has no entries for the commands,
    // and Tauri REJECTS every invoke coming from a remote origin
    // (https://x.com) with "Command ... not allowed by ACL" — which silently
    // disabled ALL native media saving and browser hand-off.
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "open_external_url",
            "prepare_download_folder",
            "download_media",
            "save_media_bytes",
        ]),
    ))
    .expect("failed to run tauri-build");
}
