fn main() {
    // Declaring the app commands makes tauri-build auto-generate
    // `permissions/autogenerated/allow-*.toml` files for each command.
    // Without them, the app's ACL manifest has no entries for the commands,
    // and Tauri REJECTS every invoke coming from a remote origin
    // (https://x.com) with "Command ... not allowed by ACL" — which silently
    // disabled ALL native media saving and browser hand-off.
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "open_external_url",
            "prepare_download_folder",
            "download_media",
            "save_media_bytes",
        ]),
    ))
    .expect("failed to run tauri-build");
}
